apiVersion: v1
kind: Service
metadata:
  name: my-html-page-service
spec:
  selector:
    app: my-html-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Or NodePort if LoadBalancer is not available in your cluster