apiVersion: v1
kind: Service
metadata:
  name: my-node-backend-service
spec:
  selector:
    app: my-node-backend
  ports:
    - protocol: TCP
      port: 5000      # The port Kubernetes Service listens on
      targetPort: 5000 # The port your container exposes
  # Change type from ClusterIP to NodePort or LoadBalancer
  type: NodePort # OR LoadBalancer (recommended for cloud, if available)